import { useEffect, useMemo } from 'react';
import { useGrip, useGripSetter } from '@owebeeone/grip-react';
import { RAW_STATUS_JSON, SHOW_SPLASH_TAP, SHOW_SPLASH_AUTO, SHOW_SPLASH_AUTO_TAP } from '../grips';

export default function Splash() {
  const status = useGrip(RAW_STATUS_JSON);
  const setShowSplash = useGripSetter(SHOW_SPLASH_TAP);
  const setShowSplashAuto = useGripSetter(SHOW_SPLASH_AUTO_TAP);
  const auto = useGrip(SHOW_SPLASH_AUTO);

  const repos = useMemo(() => {
    const set = new Set<string>();
    const list: string[] = [];
    for (const m of status?.module_status ?? []) {
      const repo = m?.source_repo?.repo_name as string | undefined;
      if (repo && !set.has(repo)) { set.add(repo); list.push(repo); }
    }
    list.sort();
    return list;
  }, [status]);

  useEffect(() => {
    if (!auto) return;
    if (!repos || repos.length === 0) return;
    const t = setTimeout(() => {
      setShowSplash(false);
      setShowSplashAuto(false);
    }, 6000);
    return () => clearTimeout(t);
  }, [repos, auto, setShowSplash, setShowSplashAuto]);

  return (
    <div className="absolute inset-0 z-20 bg-black/80 text-gray-100 flex items-center justify-center">
      <div className="relative max-w-3xl w-[90%] bg-gray-900 border border-gray-700 rounded-lg shadow-xl p-6">
        <button
          onClick={() => { setShowSplash(false); setShowSplashAuto(false); }}
          className="absolute top-2 right-2 px-2 py-1 text-sm bg-gray-700 rounded hover:bg-gray-600"
          aria-label="Close"
        >
          ✕
        </button>
        <div className="flex items-center gap-3 mb-4">
          <div className="w-12 h-12 flex-shrink-0">
            <img src="/anchor-icon.svg" alt="AnchorSCAD" className="w-full h-full" />
          </div>
          <div>
            <h2 className="text-xl font-bold">Welcome to AnchorSCAD Browser</h2>
            <p className="text-sm text-gray-400">Navigate your CAD models with precision</p>
          </div>
        </div>
        <p className="text-sm mb-4">
          This viewer showcases models generated by the <code>anchorscad-runner</code> script.
          Browse modules on the left and inspect outputs (PNG, STL, 3MF, Python code, 
          Openscad code, Paths and logs) on the right.
        </p>
        <h3 className="font-semibold mb-2">Source repositories</h3>
        <div className="space-y-2 mb-4">
          <div>
            <a 
              href="https://github.com/owebeeone/anchorscad-core" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-blue-400 hover:text-blue-300 underline font-mono"
            >
              anchorscad-core
            </a>
            <p className="text-xs text-gray-400 ml-0">
              Primary repository containing the AnchorSCAD Python API for generating OpenSCAD source code and 3D models
            </p>
          </div>
          <div>
            <a 
              href="https://github.com/owebeeone/anchorscad-viewer" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-blue-400 hover:text-blue-300 underline font-mono"
            >
              anchorscad-viewer
            </a>
            <p className="text-xs text-gray-400 ml-0">
              React single-page application that provides this interactive viewer interface
            </p>
          </div>
        </div>
        <h3 className="font-semibold mb-1">Loaded repositories</h3>
        {repos.length === 0 ? (
          <p className="text-gray-400">Loading repositories…</p>
        ) : (
          <ul className="list-disc list-inside space-y-1 max-h-32 overflow-auto">
            {repos.map((r) => (
              <li key={r}><span className="font-mono">{r}</span></li>
            ))}
          </ul>
        )}
        {auto && (
          <p className="text-xs text-gray-400 mt-4">This splash will close automatically after the repositories are loaded.</p>
        )}
      </div>
    </div>
  );
}


